[package]
name = "toml-and-jerry"
version = "1.0.3"
edition = "2021"
authors = ["Cory Janowski"]
description = "Polyglot config validator."
license = "MIT"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive", "cargo"] }
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
toml = "0.8.19"
toml_edit = { version = "0.22.22", features = ["serde"] }
hcl-rs = "0.18.0"
jsonschema = "0.30.0"
miette = { version = "7.6.0", features = ["fancy"] }
reqwest = { version = "0.12.8", features = ["blocking", "json"] }
rayon = "1.10.0"
ignore = "0.4.23"
serde_yaml = "0.9.34"
thiserror = "2.0.1"
json-spanned-value = "0.2.2"
serde-sarif = "0.8.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
walkdir = "2.5.0"

[dev-dependencies]
