[package]
name = "toml-and-jerry"
version = "1.0.2"
edition = "2021"
authors = ["Cory Janowski"]
description = "Polyglot config validator."
license = "MIT"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml_edit = "0.22"
hcl-rs = "0.14"
jsonschema = "0.17"
miette = { version = "5.10.0", features = ["fancy"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
rayon = "1.8"
ignore = "0.4"
